### PR TITLE
Always store thumbnails as JPEG 99662722

### PR DESCRIPTION
**Pull request by frediy**
When an image is uploaded on radio and thumbnails are generated, they should always be converted to JPEG. The original should be kept in PNG or whatever format it is uploaded in.

https://www.pivotaltracker.com/story/show/99662722

### CODE REVIEW

**Comment by michaelwebb76** [comment]
I don't want to be a party pooper - what you've done looks okay. But I kinda sorta think that maybe, just maybe, there should be some specs.

**Comment by frediy** [comment]
Cool, I'll have a look a unit test for attachment fu. If it turns out to be a huge hassle, I might just cover it with a feature spec in radio.

**Comment by michaelwebb76** [comment]
Sounds fair. Doesn't look like it's rspecced

**Comment by frediy** [comment]
Nah they're using test unit. I played around with the test suite and couldn't get it to run. I found this bit actually committed in one of the tests:

```
<<<<<<< HEAD
  def after_resize(img)
    self.aspect_ratio = img.columns.to_f / img.rows.to_f
  end
=======
  # after_resize do |record, img|
  #   record.aspect_ratio = img.columns.to_f / img.rows.to_f
  # end
>>>>>>> 33222f02ee9657d0ea9e4654b06cea7ed49cb85b
```

I think it makes sense to just do a feature spec and not rely on trying to get that test suite to run. Does not look like it is maintained, which is a bit worrying. We should always evaluate the quality of the specs before we start using third party code.

**Comment by michaelwebb76** [comment]
Yep. https://bellroywiki.trikeapps.com/display/TRIKE/Holy+Commandments+of+3rd+Party+Project+Use

**Pull request merged**
